// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs-Q1NAE6m_yEOU2U8kDMeO4-h-DhNHJQ',
    appId: '1:830604967154:web:bb61affc0327145ccae46b',
    messagingSenderId: '830604967154',
    projectId: 'claro-project-1f0a0',
    authDomain: 'claro-project-1f0a0.firebaseapp.com',
    storageBucket: 'claro-project-1f0a0.appspot.com',
    measurementId: 'G-TKVR1H4B3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2gv3ffrGqV8w2L5CcHid7ebUictEq84c',
    appId: '1:830604967154:android:ca28f5fc1ea71202cae46b',
    messagingSenderId: '830604967154',
    projectId: 'claro-project-1f0a0',
    storageBucket: 'claro-project-1f0a0.appspot.com',
  );
}
